on: [push, pull_request]
name: test
jobs:
  validate:
    runs-on: ubuntu-latest
    container: macintoshprime/kubectl:v1.17
    steps:
      - uses: actions/checkout@v1
      - name: Validate kustomization
        run: |
            echo "Validating install"
            kustomize build install | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster"
            kustomize build cluster | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster/flagger"
            kustomize build cluster/flagger | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster/gatekeeper"
            kustomize build cluster/gatekeeper | kubeval --strict --ignore-missing-schemas
      - name: Deny latest container image tags
        run: |
            kustomize build cluster | conftest test -p .github/policy -
name: Kind ## From https://github.com/kind-ci/examples/blob/master/.github/workflows/kind.yml
on: [push, pull_request]
jobs:
  test-unit:
    name: Create a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide