on: [push, pull_request]
name: test
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate kustomization
        uses: macintoshprime/kubectl@v1.17
        with:
          command: |
            echo "Validating install"
            kustomize build install | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster"
            kustomize build cluster | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster/flagger"
            kustomize build cluster/flagger | kubeval --strict --ignore-missing-schemas
            echo "Validating cluster/gatekeeper"
            kustomize build cluster/gatekeeper | kubeval --strict --ignore-missing-schemas
      - name: Deny latest container image tags
        uses: macintoshprime/kubectl@v1.17
        with:
          command: |
            kustomize build cluster | conftest test -p .github/policy -
